  name: Mobile App Publish
  run-name: "Mobile Publish: ${{ github.event.inputs.projectName }}"

  on:
    workflow_dispatch:
      inputs:
        runOn:
          description: 'Run on Android or iOS'
          required: true
        projectName:
          description: 'Project Name'
          required: true
        project_url:
          description: 'Git repo URL (omit https://)'
          required: true

  jobs:
    android:
      if: ${{ github.event.inputs.runOn == 'android' || github.event.inputs.runOn == 'both' }}
      runs-on: ubuntu-latest
      
      env:
        FLUTTER_HOME: ~/.flutter

      steps:
        - name: Create Flutter Version File
          run: echo "3.29.2" > flutter_version.txt

        - name: Check Secrets (safe debug)
          run: |
            echo "PAT is set: ${TPAT_GITHUB:+yes}"
          env:
            TPAT_GITHUB: ${{ secrets.TPAT_GITHUB }}

        # ------------------ Repo setup ------------------
        - name: Checkout this GitHub repo
          uses: actions/checkout@v4

        - name: Clone Azure DevOps project
          run: |
            git config --global http.sslVerify false
            git clone --branch master https://${TPAT_GITHUB}@${{ github.event.inputs.project_url }} project
          env:
            TPAT_GITHUB: ${{ secrets.TPAT_GITHUB }}
